# 是否启用本插件
enable-whitelist: true
# 当玩家没有在白名单里的时候被T出显示的文字（支持颜色代号&)
# 引号不能丢，不能换中文引号
nwm: "&4您没有在白名单内！"

# 当你用指令删掉（必须是指令，不能是直接在下面删除）玩家的时候
# 如果玩家还在线，会强制T出，并显示下列文字（支持颜色代号&）
bwm: "&4您因为违反了服务器规矩被撤销白名单"

# 白名单
# 注意：1、此列表不能为空
# 2、请把玩家名字用英文双引号引起来(不要用中文双引号“”，要用英文双引号"")
whitelisted-players:
  - "X_huihui"